### ISSUE TITLE
LKSMART.sql

### ISSUE THREAD

**Issue by XDRYX** [gavrielsatrio/LKSMart#1]
Hallo mas, boleh module lksnya untuk saya & next adik adik saya latihan?

**Comment by gavrielsatrio** [comment]
> Hallo mas, boleh module lksnya untuk saya & next adik adik saya latihan?

Halo juga Mas. Boleh Mas...., Sekalian nambah bank soal juga untuk adik-adik generasi kedepannya 😁🙏. Salam kenal Mas.... 🙏😄
